### ISSUE TITLE
pip install failing on linux, not sure quite why

### ISSUE THREAD

**Issue by cfe316** [hiddenSymmetries/booz_xform#12]
Dear booz_xform, I'm trying to install booz_xform using pip but it's failing. Here's my system specifications, let me know if there's anything else I might try.

I'm running `Pop!_OS 22.04`
Kernel `6.0.12- ....`
Python `3.10.2`, in a new virtual environment. I previously did `pip install "simsopt[MPI,SPEC]"` which succeeded. Pip freeze gives
```
Deprecated==1.2.13
f90nml==1.4.3
h5py==3.8.0
jax==0.4.4
jaxlib==0.4.4
monty==2022.9.9
mpi4py==3.1.4
mpmath==1.2.1
nptyping==2.5.0
numpy==1.24.2
opt-einsum==3.3.0
py-spec==3.1.0
pybind11==2.10.3
pyevtk==1.5.0
pyoculus==0.1.3
randomgen==1.23.1
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scipy==1.10.1
simsopt==0.12.2
sympy==1.11.1
wrapt==1.14.1
```
cmake version `3.22.1`

gcc / g++ are `(Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0`

I know I need NetCDF. `apt list --installed | grep netcdf`:

```
libnetcdf-dev/jammy,now 1:4.8.1-1 amd64 [installed]
libnetcdf-mpi-19/jammy,now 1:4.8.1-2 amd64 [installed]
libnetcdf-mpi-dev/jammy,now 1:4.8.1-2 amd64 [installed]
libnetcdf-pnetcdf-19/jammy,now 1:4.8.1-2 amd64 [installed,automatic]
libnetcdf-pnetcdf-dev/jammy,now 1:4.8.1-2 amd64 [installed]
libnetcdf19/jammy,now 1:4.8.1-1 amd64 [installed,automatic]
libpnetcdf0d/jammy,now 1.12.2-1 amd64 [installed,automatic]
```
(I probably installed too many here...)

Looking at the build log, it is able to find pybind11 (2.10.3)
Here's the section of the build log where errors begin:

```
<appears to be successful up to here>

  [10/21] Building CXX object CMakeFiles/libbooz_xform.dir/src/_booz_xform/run.cpp.o
  [11/21] Building CXX object CMakeFiles/libbooz_xform.dir/src/_booz_xform/read_wout.cpp.o
  [12/21] Building CXX object CMakeFiles/unitTests.dir/tests/driver_tests.cpp.o
  FAILED: CMakeFiles/unitTests.dir/tests/driver_tests.cpp.o
  /usr/bin/c++ -DOPENMP -I/tmp/pip-install-pik5pjxv/booz-xform_a133ab4596d54332ab041b59b2fd9ba1/src/_booz_xform -I/tmp/pip-install-pik5pjxv/bo
oz-xform_a133ab4596d54332ab041b59b2fd9ba1/externalPackages/doctest -I/tmp/pip-install-pik5pjxv/booz-xform_a133ab4596d54332ab041b59b2fd9ba1/ext
ernalPackages/eigen -g   -O2 -ftemplate-depth=1024 -fopenmp -std=gnu++11 -MD -MT CMakeFiles/unitTests.dir/tests/driver_tests.cpp.o -MF CMakeFi
les/unitTests.dir/tests/driver_tests.cpp.o.d -o CMakeFiles/unitTests.dir/tests/driver_tests.cpp.o -c /tmp/pip-install-pik5pjxv/booz-xform_a133
ab4596d54332ab041b59b2fd9ba1/tests/driver_tests.cpp
  In file included from /tmp/pip-install-pik5pjxv/booz-xform_a133ab4596d54332ab041b59b2fd9ba1/tests/driver_tests.cpp:3:
  /tmp/pip-install-pik5pjxv/booz-xform_a133ab4596d54332ab041b59b2fd9ba1/externalPackages/doctest/doctest.h:4189:47: error: size of array ‘altS
tackMem’ is not an integral constant-expression
   4189 |         static char             altStackMem[4 * SIGSTKSZ];
        |                                               ^
  [13/21] Building CXX object CMakeFiles/xbooz_xform.dir/src/_booz_xform/xbooz_xform.cpp.o
  [14/21] Building CXX object CMakeFiles/unitTests.dir/tests/init_trig_tests.cpp.o
  [15/21] Building CXX object CMakeFiles/libbooz_xform.dir/src/_booz_xform/surface_solve.cpp.o
  [16/21] Building CXX object CMakeFiles/libbooz_xform.dir/src/_booz_xform/write_boozmn.cpp.o
  [17/21] Building CXX object CMakeFiles/_booz_xform.dir/src/_booz_xform/bindings.cpp.o
  ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "/home/jacob/.pyenv/versions/3.10.2/envs/hiddensymm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.
py", line 353, in <module>
      main()
    File "/home/jacob/.pyenv/versions/3.10.2/envs/hiddensymm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.
py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
      
 <more traceback>
 
    File "<string>", line 102, in build_extension
    File "/home/jacob/.pyenv/versions/3.10.2/lib/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 1.
  error: subprocess-exited-with-error

  × Building wheel for booz_xform (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/jacob/.pyenv/versions/3.10.2/envs/hiddensymm/bin/python3.10 /home/jacob/.pyenv/versions/3.10.2/envs/hiddensymm/lib/pytho
n3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpwxd7hnps
  cwd: /tmp/pip-install-pik5pjxv/booz-xform_a133ab4596d54332ab041b59b2fd9ba1
  Building wheel for booz_xform (pyproject.toml) ... error
  ERROR: Failed building wheel for booz_xform
Failed to build booz_xform
ERROR: Could not build wheels for booz_xform, which is required to install pyproject.toml-based projects

```

Is there something I should install, enable or disable somewhere so that the package can build?

**Comment by landreman** [comment]
It looks like the error is related to the doctest package. Seems that other people have experienced a similar error [here](https://github.com/doctest/doctest/issues/473). I just updated booz_xform to use the latest doctest, which should be available in a new booz_xform version 0.0.8. Let me know if that fixes the issue on your end.

**Comment by cfe316** [comment]
It succeeded now with `pip install --upgrade -v`. Thank you very much!
